version: '3'
services:
  labs:
    build: .
    image: sjawhar/omscs-hpc
    container_name: omscs-hpc
    volumes:
      - "./:/omscs"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=10.0.75.1:0"
    tty: true
    command: ["/bin/bash"]
