version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.assignments
    image: sjawhar/omscs-cp-assignments
    container_name: omscs-cp-assignments
    volumes:
      - "./:/omscs"
    ports:
      - "8888"
    command:
      - "--NotebookApp.token=''"
      - "--NotebookApp.iopub_data_rate_limit=10000000000"
