version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.labs
    image: sjawhar/omscs-cp-labs
    container_name: omscs-cp-labs
    volumes:
      - "./:/home/jovyan/work"
    ports:
      - "8888"
    command: ["start-notebook.sh", "--NotebookApp.token=''"]

